### PR TITLE
Blog app - Add forms

### PR DESCRIPTION
**Pull request by MarcoDiaz2000**
## Description
In this project, I added forms to my Blog app.

### Project requirements
-  Create a method called `current_user` in your ApplicationController to make current user data available to all controllers.
    -  It will return the first user from the database.
    -  Don't worry about proper authentication at this time. You will add it in the upcoming projects.
- Create forms to perform the following functions:
    - Creates a Post on behalf of the `current_user` (use the method that you created in your ApplicationController).
    - Create a comment on behalf of the `current_user` (use the method that you created in your ApplicationController).
- Allow Users to add likes to Posts.

### CODE REVIEW

**Review by Ibizugbe — CHANGES_REQUESTED** [review]
Hi @MarcoDiaz2000 👋🏼👋🏼👋🏼👋🏼, 

require_changes


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅✅

- [x] The application controller contains the currentUser method👍🏼.
- [x] The post controller has new and create actions👍🏼.
- [x] Linters are passing👍🏼.





## Required Changes ♻️

- [ ] Nice job so far👍🏼. It happens that even after adding some users to the data base both on the console and making use of the seed, the user index page still renders a blank page🥲 even after changing the path mannualy as you can see on the image below. Kindly do well to fix that as this can lead to a bad user experience. also, this is the only way one can test whether the form works properly👍🏼.
Screenshot 2023-08-25 at 09 12 28
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MarcoDiaz2000** [comment]
Hi @Ibizugbe 

Could you tell me if you get any error, because in my computer it works fine.
user1
user2

**Comment by Ibizugbe** [comment]
@MarcoDiaz2000 I actually didn't get any error. as you can see on the image I have uploaded.
do you mind if we get on a call together, so we can go through it?

**Comment by MarcoDiaz2000** [comment]
Hi @Ibizugbe 

I am checking and apparently I have a problem with the creation of new users.
I will fix it.

Thanks

**Comment by Ibizugbe** [comment]
Alright @MarcoDiaz2000 👋🏼.

when you solve the issue, and you have resubmitted, I will suggest you stay online both on slack and zoom just incase a reviewer wants to reach out to you😉.

**Comment by MarcoDiaz2000** [comment]
> Thanks @Ibizugbe  👋🏼

**Review by elisha2kyakpo1 — APPROVED** [review]
Hi 👋 @MarcoDiaz2000, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👋 Great job fixing the issue with the user's page as requested by the previous reviewer, the app works perfectly.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MarcoDiaz2000** [comment]
Thanks @elisha2kyakpo1

**Pull request merged**
